// <auto-generated />
using System;
using System.Collections.Generic;
using EduTests.Database;
using EduTests.Database.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduTests.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260320182028_RemoveSomeRequireds")]
    partial class RemoveSomeRequireds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "AccessType", new[] { "private", "public", "unlisted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "QuestionType", new[] { "match_pairs", "multiple_choice", "number_input", "sequence", "single_choice", "text_input" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ReportStatus", new[] { "accepted", "pending", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "UserGroup", new[] { "administrator", "moderator", "user" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduTests.Database.Entities.BannedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BanReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ban_reason");

                    b.Property<int>("BannedById")
                        .HasColumnType("integer")
                        .HasColumnName("banned_by_id");

                    b.Property<DateTime>("DateBanned")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_banned");

                    b.Property<DateTime?>("DateUnbanned")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_unbanned");

                    b.Property<int>("UserBannedId")
                        .HasColumnType("integer")
                        .HasColumnName("user_banned_id");

                    b.HasKey("Id")
                        .HasName("pk_banned_users");

                    b.HasIndex("BannedById")
                        .HasDatabaseName("ix_banned_users_banned_by_id");

                    b.HasIndex("UserBannedId")
                        .HasDatabaseName("ix_banned_users_user_banned_id");

                    b.ToTable("banned_users", (string)null);
                });

            modelBuilder.Entity("EduTests.Database.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommenterId")
                        .HasColumnType("integer")
                        .HasColumnName("commenter_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("CommenterId")
                        .HasDatabaseName("ix_comments_commenter_id");

                    b.HasIndex("TestId")
                        .HasDatabaseName("ix_comments_test_id");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("ix_comments_user_profile_id");

                    b.ToTable("comments", null, t =>
                        {
                            t.HasCheckConstraint("SingleTargetCheckComment", "(test_id IS NULL AND user_profile_id IS NOT NULL) OR (test_id IS NOT NULL AND user_profile_id IS NULL)");
                        });
                });

            modelBuilder.Entity("EduTests.Database.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.Property<QuestionType>("Type")
                        .HasColumnType("\"QuestionType\"")
                        .HasColumnName("type");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CorrectData", "EduTests.Database.Entities.Question.CorrectData#QuestionData", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<string>("LeftColumn")
                                .IsRequired();

                            b1.Property<double?>("NumberAnswer");

                            b1.PrimitiveCollection<string>("Options")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("RightColumn")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Sequence")
                                .IsRequired();

                            b1.Property<string>("TextAnswer");

                            b1.Property<double?>("Tolerance");

                            b1.PrimitiveCollection<string>("ValidAnswers")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Pairs", "EduTests.Database.Entities.Question.CorrectData#QuestionData.Pairs#MatchingPair", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Left")
                                        .IsRequired();

                                    b2.Property<string>("Right")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("correct_data")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Data", "EduTests.Database.Entities.Question.Data#QuestionData", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<string>("LeftColumn")
                                .IsRequired();

                            b1.Property<double?>("NumberAnswer");

                            b1.PrimitiveCollection<string>("Options")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("RightColumn")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Sequence")
                                .IsRequired();

                            b1.Property<string>("TextAnswer");

                            b1.Property<double?>("Tolerance");

                            b1.PrimitiveCollection<string>("ValidAnswers")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Pairs", "EduTests.Database.Entities.Question.Data#QuestionData.Pairs#MatchingPair", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Left")
                                        .IsRequired();

                                    b2.Property<string>("Right")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("data")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("TestId")
                        .HasDatabaseName("ix_questions_test_id");

                    b.ToTable("questions", null, t =>
                        {
                            t.HasCheckConstraint("order_index_check", "order_index >= 1");
                        });
                });

            modelBuilder.Entity("EduTests.Database.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time");

                    b.Property<ReportStatus>("ReportStatus")
                        .HasColumnType("\"ReportStatus\"")
                        .HasColumnName("report_status");

                    b.Property<int?>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_reports_comment_id");

                    b.HasIndex("TestId")
                        .HasDatabaseName("ix_reports_test_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reports_user_id");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("SingleTargetCheckReport", "(test_id IS NOT NULL AND user_id IS NULL AND comment_id IS NULL) OR (test_id IS NULL AND user_id IS NOT NULL AND comment_id IS NULL) OR (test_id IS NULL AND user_id IS NULL AND comment_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("EduTests.Database.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("EduTests.Database.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<AccessType>("AccessType")
                        .HasColumnType("\"AccessType\"")
                        .HasColumnName("access_type");

                    b.Property<int?>("AttemptLimit")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_limit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<TimeSpan?>("TimeLimit")
                        .HasColumnType("interval")
                        .HasColumnName("time_limit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tests");

                    b.HasIndex("Description")
                        .HasDatabaseName("ix_tests_description");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tests_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tests_user_id");

                    b.ToTable("tests", null, t =>
                        {
                            t.HasCheckConstraint("attempt_limit_check", "attempt_limit IS NULL OR (attempt_limit >= 0 AND attempt_limit <= 10)");

                            t.HasCheckConstraint("time_limit_check", "time_limit IS NULL OR (time_limit >= '0 hours'::interval AND time_limit <= '5 hours'::interval)");
                        });
                });

            modelBuilder.Entity("EduTests.Database.Entities.TestCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<float>("CompletionPercentage")
                        .HasColumnType("real")
                        .HasColumnName("completion_percentage");

                    b.Property<TimeSpan>("CompletionTime")
                        .HasColumnType("interval")
                        .HasColumnName("completion_time");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<int>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_test_completions");

                    b.HasIndex("TestId")
                        .HasDatabaseName("ix_test_completions_test_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_test_completions_user_id");

                    b.ToTable("test_completions", null, t =>
                        {
                            t.HasCheckConstraint("answer_count_check", "correct_answers >= 0");

                            t.HasCheckConstraint("completion_percentage_check", "completion_percentage >= 0 AND completion_percentage <= 100");
                        });
                });

            modelBuilder.Entity("EduTests.Database.Entities.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("PercentageThreshold")
                        .HasColumnType("real")
                        .HasColumnName("percentage_threshold");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<int>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.HasKey("Id")
                        .HasName("pk_test_results");

                    b.HasIndex("TestId")
                        .HasDatabaseName("ix_test_results_test_id");

                    b.ToTable("test_results", null, t =>
                        {
                            t.HasCheckConstraint("threshold_check", "percentage_threshold >= 0 AND percentage_threshold <= 100");
                        });
                });

            modelBuilder.Entity("EduTests.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<UserGroup>("Group")
                        .HasColumnType("\"UserGroup\"")
                        .HasColumnName("group");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_users_login");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EduTests.Database.Entities.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("TestCompletionId")
                        .HasColumnType("integer")
                        .HasColumnName("test_completion_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Answers", "EduTests.Database.Entities.UserAnswer.Answers#QuestionData", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<string>("LeftColumn")
                                .IsRequired();

                            b1.Property<double?>("NumberAnswer");

                            b1.PrimitiveCollection<string>("Options")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("RightColumn")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Sequence")
                                .IsRequired();

                            b1.Property<string>("TextAnswer");

                            b1.Property<double?>("Tolerance");

                            b1.PrimitiveCollection<string>("ValidAnswers")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Pairs", "EduTests.Database.Entities.UserAnswer.Answers#QuestionData.Pairs#MatchingPair", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Left")
                                        .IsRequired();

                                    b2.Property<string>("Right")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("answers")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_user_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_user_answers_question_id");

                    b.HasIndex("TestCompletionId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_answers_test_completion_id_question_id");

                    b.ToTable("user_answers", (string)null);
                });

            modelBuilder.Entity("EduTests.Database.Entities.UserRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPositive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_positive");

                    b.Property<int>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_rating");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_rating_user_id");

                    b.HasIndex("TestId", "IsPositive")
                        .HasDatabaseName("ix_user_rating_test_id_is_positive");

                    b.HasIndex("TestId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_rating_test_id_user_id");

                    b.ToTable("user_rating", (string)null);
                });

            modelBuilder.Entity("TagTest", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("integer")
                        .HasColumnName("tags_id");

                    b.Property<int>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.HasKey("TagsId", "TestId")
                        .HasName("pk_tag_test");

                    b.HasIndex("TestId")
                        .HasDatabaseName("ix_tag_test_test_id");

                    b.ToTable("tag_test", (string)null);
                });

            modelBuilder.Entity("EduTests.Database.Entities.BannedUser", b =>
                {
                    b.HasOne("EduTests.Database.Entities.User", "BannedBy")
                        .WithMany()
                        .HasForeignKey("BannedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_banned_users_users_banned_by_id");

                    b.HasOne("EduTests.Database.Entities.User", "UserBanned")
                        .WithMany()
                        .HasForeignKey("UserBannedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_banned_users_users_user_banned_id");

                    b.Navigation("BannedBy");

                    b.Navigation("UserBanned");
                });

            modelBuilder.Entity("EduTests.Database.Entities.Comment", b =>
                {
                    b.HasOne("EduTests.Database.Entities.User", "Commenter")
                        .WithMany()
                        .HasForeignKey("CommenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_commenter_id");

                    b.HasOne("EduTests.Database.Entities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .HasConstraintName("fk_comments_tests_test_id");

                    b.HasOne("EduTests.Database.Entities.User", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .HasConstraintName("fk_comments_users_user_profile_id");

                    b.Navigation("Commenter");

                    b.Navigation("Test");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("EduTests.Database.Entities.Question", b =>
                {
                    b.HasOne("EduTests.Database.Entities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_tests_test_id");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("EduTests.Database.Entities.Report", b =>
                {
                    b.HasOne("EduTests.Database.Entities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .HasConstraintName("fk_reports_comments_comment_id");

                    b.HasOne("EduTests.Database.Entities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .HasConstraintName("fk_reports_tests_test_id");

                    b.HasOne("EduTests.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_reports_users_user_id");

                    b.Navigation("Comment");

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTests.Database.Entities.Test", b =>
                {
                    b.HasOne("EduTests.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tests_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTests.Database.Entities.TestCompletion", b =>
                {
                    b.HasOne("EduTests.Database.Entities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_completions_tests_test_id");

                    b.HasOne("EduTests.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_completions_users_user_id");

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTests.Database.Entities.TestResult", b =>
                {
                    b.HasOne("EduTests.Database.Entities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_results_tests_test_id");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("EduTests.Database.Entities.UserAnswer", b =>
                {
                    b.HasOne("EduTests.Database.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_answers_questions_question_id");

                    b.HasOne("EduTests.Database.Entities.TestCompletion", "Completion")
                        .WithMany()
                        .HasForeignKey("TestCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_answers_test_completions_test_completion_id");

                    b.Navigation("Completion");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EduTests.Database.Entities.UserRating", b =>
                {
                    b.HasOne("EduTests.Database.Entities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_rating_tests_test_id");

                    b.HasOne("EduTests.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_rating_users_user_id");

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TagTest", b =>
                {
                    b.HasOne("EduTests.Database.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_test_tags_tags_id");

                    b.HasOne("EduTests.Database.Entities.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_test_tests_test_id");
                });
#pragma warning restore 612, 618
        }
    }
}
